language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: nWRgEXG/dHoFrnjm1emSEQVks0j8bnF2nFg+Q1CqUxW2xwZtyhkIG5Itza5U92SAGzx++dXoGwsqMxNZvAgCWqCaWSCwHf7lJnXFl/eDkalkHe+an7nfSsFa3s3CZTQercNNv62YszNoTB6eYfrRbWbf0lcgGTb/4KfmEDNReiCPtjQ4sI8j+uNWeY1NbRDs3qJeO7GY61/z+s3gjN1GrU2eQ4nOMDTkkdz4uMEB88Kg4Tp7Z5b1u//bZNjIxsxDOiynKFgVLHdOO8cNo4WgcaojjkLOstncAKp/wz9OjunhQGYIh3mBE4FY36A6Vj6hfXB2vNxgFeTspqpstqSQYBCnOPbkrOCn/Rsg9QMjyaK1C91PbsVtpzbjfk/t45BVwy/BQzc2N6WWOhhdZdi8FXdpQI/nU4fyQk0msCK/A9EcHEDsJY+LS0LMnU7ZlEt+h8Pu2gaW72D2D/MioyTAwtPchh5zC44S5sqz8Ym+Cb4bdOTsiV2PogC95/GabWIBwpar5hPuLrKoqzGm+dD0z0vrAizZqdkpWYOcCLkbjxRuExfmrPg9nMbif+yXEznH2/l5hcNy4yS3wtcOJ6+CRpJU0t4m+5y7wdSFXFBNr6FW4fv+UNOEM6ozq2mp2YecXhhGIPN+/2WBZRJj60vw4lfCzrcBkFP995w4XeWeVDw=
  app: immense-mountain-98094
  on:
    repo: jayshol/puzzle-node-server
